version: 3.18.0.{build}
configuration: Release
#platform: Any CPU
platform:
  - x86
  - x64
build:
  project: NuGetPackageExplorer.sln
  verbosity: minimal
after_build:
- ps: >-
    choco pack PackageExplorer\NugetPackageExplorer.nuspec --version 3.18

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\*.nupkg'
deploy:
  release: NuGetPackageExplorer-v$(appveyor_repo_tag)
  description: 'NuGetPackageExplorer Release'
  provider: GitHub
  auth_token:
    secure: <39c2f294ac9bdc28adc46923639443548cfc4d32> # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
